#!/usr/bin/env python3
# VergeGrid Database Setup Utility
# Author: Sonja + Code GPT
# Responsible for generating MySQL config, initializing data directory,
# creating the VergeGridMySQL Windows service, setting the root password,
# storing the hashed password for maintenance, and performing health checks.

# --- Ensure local setup scripts can find vergegrid_common ---
import sys, os
if getattr(sys, 'frozen', False):
    base_dir = os.path.dirname(sys.executable)
else:
    base_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(base_dir)

import subprocess
import time
import re
import shutil
import hashlib
from pathlib import Path
from colorama import Fore, Style
from vergegrid_common import _get_logger

# ============================================================
# Templates
# ============================================================

MYSQL_TEMPLATE = r"""
# VergeGrid MySQL Configuration
# Auto-generated by VergeGrid Installer
# Adjust parameters only if you know what you're doing.

[client]
port=3306
socket="%(root)s\\MySQL\\mysql.sock"

[mysql]
default-character-set=utf8mb4

[mysqld]
basedir="%(root)s\\MySQL"
datadir="%(root)s\\MySQL\\data"
port=3306
socket="%(root)s\\MySQL\\mysql.sock"
pid_file="%(root)s\\MySQL\\data\\mysql.pid"
log_error="%(root)s\\MySQL\\data\\mysql.err"

# Character Encoding
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

# Performance Tweaks
max_connections=500
connect_timeout=15
wait_timeout=28800
interactive_timeout=28800
innodb_buffer_pool_size=512M
innodb_redo_log_capacity=536870912
innodb_flush_log_at_trx_commit=2
innodb_file_per_table=1
innodb_flush_method=normal
innodb_lock_wait_timeout=120

# Logging
log-bin="%(root)s\\MySQL\\data\\mysql-bin"
binlog_format=row
binlog_expire_logs_seconds=604800

# VergeGrid Specific
sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
server-id=1
"""

# ============================================================
# Helpers
# ============================================================

def run_cmd(cmd):
    """Run a command and return success and output."""
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, shell=False)
        return result.returncode == 0, (result.stdout or result.stderr).strip()
    except Exception as e:
        return False, str(e)

def get_mysql_version(mysqld_path: Path) -> str:
    """Return MySQL version string (e.g. '8.4.6') or empty string on failure."""
    try:
        result = subprocess.run([str(mysqld_path), "--version"], capture_output=True, text=True)
        match = re.search(r"(\d+\.\d+\.\d+)", result.stdout)
        return match.group(1) if match else ""
    except Exception:
        return ""

# ============================================================
# MySQL Config Generation
# ============================================================

def generate_mysql_ini(root: Path):
    """Generate VergeGrid MySQL configuration file."""
    log = _get_logger()
    conf_path = root / "MySQL" / "my.ini"
    conf_text = MYSQL_TEMPLATE % {"root": str(root)}

    try:
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(conf_text, encoding="utf-8")
        log(Fore.GREEN + f"[OK] Created MySQL config: {conf_path}" + Fore.RESET)
        return conf_path
    except Exception as e:
        log(Fore.RED + f"[ERROR] Failed to write MySQL config: {e}" + Fore.RESET)
        return None

# ============================================================
# MySQL Data Initialization
# ============================================================

def ensure_writable_path(path: Path):
    """Ensure that a file or directory is writable, remove read-only, and fix ACLs."""
    log = _get_logger()
    try:
        if not path.exists():
            return True
        subprocess.run(["attrib", "-R", str(path)], capture_output=True)
        subprocess.run(["icacls", str(path), "/setowner", "Administrators"], capture_output=True)
        subprocess.run(["icacls", str(path), "/grant", "Everyone:(OI)(CI)F", "/T"], capture_output=True)
        subprocess.run(["icacls", str(path), "/grant", "Users:(OI)(CI)F", "/T"], capture_output=True)
        if path.is_dir():
            testfile = path / "__writetest.tmp"
            try:
                with open(testfile, "w") as f:
                    f.write("ok")
                testfile.unlink(missing_ok=True)
                return True
            except Exception as e:
                log(Fore.YELLOW + f"[WARN] Unable to write to {path}: {e}" + Fore.RESET)
                return False
        else:
            try:
                with open(path, "a"):
                    pass
                return True
            except Exception as e:
                log(Fore.YELLOW + f"[WARN] Cannot write to file {path}: {e}" + Fore.RESET)
                return False
    except Exception as e:
        log(Fore.RED + f"[ERROR] Permission repair failed for {path}: {e}" + Fore.RESET)
        return False

def kill_stuck_mysql_processes():
    """Terminate any existing mysqld.exe processes before reinitialization."""
    log = _get_logger()
    try:
        result = subprocess.run(["tasklist", "/FI", "IMAGENAME eq mysqld.exe"], capture_output=True, text=True)
        if "mysqld.exe" in result.stdout:
            log(Fore.YELLOW + "[CLEANUP] Found running MySQL process — terminating..." + Fore.RESET)
            subprocess.run(["taskkill", "/F", "/IM", "mysqld.exe"], capture_output=True)
            time.sleep(1)
    except Exception as e:
        log(Fore.YELLOW + f"[WARN] Failed to check or kill mysqld.exe: {e}" + Fore.RESET)

def initialize_mysql_data(root: Path):
    """Initialize MySQL data directory if empty, corrupted, or permission-locked."""
    log = _get_logger()
    data_dir = root / "MySQL" / "data"
    mysqld = root / "MySQL" / "bin" / "mysqld.exe"
    log_file = data_dir / "init_error.log"

    if not mysqld.exists():
        log(Fore.RED + f"[ERROR] mysqld.exe not found at {mysqld}" + Fore.RESET)
        return False

    os.makedirs(data_dir, exist_ok=True)
    ensure_writable_path(data_dir)
    kill_stuck_mysql_processes()

    ibdata = data_dir / "ibdata1"
    if ibdata.exists():
        ensure_writable_path(ibdata)
        try:
            if ibdata.stat().st_size == 0:
                log(Fore.YELLOW + "[WARN] ibdata1 is 0 bytes — deleting and reinitializing." + Fore.RESET)
                ibdata.unlink(missing_ok=True)
        except Exception as e:
            log(Fore.YELLOW + f"[WARN] Unable to inspect ibdata1: {e}" + Fore.RESET)

    system_db = data_dir / "mysql"
    if system_db.exists():
        system_files = list(system_db.glob("*.frm")) + list(system_db.glob("*.ibd"))
        if not system_files:
            log(Fore.YELLOW + "[WARN] MySQL system tables missing — wiping data directory." + Fore.RESET)
            shutil.rmtree(data_dir, ignore_errors=True)
            os.makedirs(data_dir, exist_ok=True)
            ensure_writable_path(data_dir)
        else:
            log(Fore.CYAN + "[INFO] MySQL data directory already initialized." + Fore.RESET)
            return True

    log(Fore.YELLOW + "[INIT] Running MySQL initialization..." + Fore.RESET)
    cmd = [
        str(mysqld),
        "--initialize-insecure",
        f"--basedir={root / 'MySQL'}",
        f"--datadir={data_dir}",
        f"--log-error={log_file}"
    ]

    try:
        with subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) as proc:
            stdout, stderr = proc.communicate(timeout=180)

        if log_file.exists():
            with open(log_file, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read().strip()
                if content:
                    log(Fore.YELLOW + f"[DEBUG] MySQL init log:\n{content}" + Fore.RESET)

        if proc.returncode == 0:
            log(Fore.GREEN + "[OK] MySQL data directory initialized successfully." + Fore.RESET)
            return True
        else:
            if "ibdata1" in stderr or "writable" in stderr.lower():
                log(Fore.YELLOW + "[AUTO-RECOVERY] ibdata1 not writable — forcing permission reset & reinit." + Fore.RESET)
                ensure_writable_path(ibdata)
                ensure_writable_path(data_dir)
                kill_stuck_mysql_processes()
                shutil.rmtree(data_dir, ignore_errors=True)
                os.makedirs(data_dir, exist_ok=True)
                ensure_writable_path(data_dir)
                return initialize_mysql_data(root)
            log(Fore.RED + f"[ERROR] MySQL initialization failed (exit {proc.returncode})." + Fore.RESET)
            if stderr.strip():
                log(Fore.RED + f"[STDERR] {stderr.strip()}" + Fore.RESET)
            return False
    except subprocess.TimeoutExpired:
        log(Fore.RED + "[ERROR] MySQL initialization timed out (180s)." + Fore.RESET)
        return False
    except Exception as e:
        log(Fore.RED + f"[FATAL] Exception during MySQL init: {e}" + Fore.RESET)
        return False

# ============================================================
# MySQL Service Creation
# ============================================================
def create_mysql_service(root: Path):
    """Use MySQL's built-in installer to create a proper Windows service."""
    log = _get_logger()
    mysqld = root / "MySQL" / "bin" / "mysqld.exe"
    ini_file = root / "MySQL" / "my.ini"

    if not mysqld.exists():
        log(Fore.RED + f"[ERROR] mysqld.exe not found at {mysqld}" + Fore.RESET)
        return False

    # Remove any stale service entry
    log(Fore.YELLOW + "[CLEANUP] Removing existing VergeGridMySQL service (if any)..." + Fore.RESET)
    subprocess.run(["sc", "stop", "VergeGridMySQL"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.run(["sc", "delete", "VergeGridMySQL"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    log(Fore.YELLOW + "[CREATE] Installing VergeGridMySQL service using mysqld --install..." + Fore.RESET)
    cmd = [
        str(mysqld),
        "--install", "VergeGridMySQL",
        f"--defaults-file={ini_file}"
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        log(Fore.RED + f"[ERROR] Failed to install MySQL service:\n{result.stderr or result.stdout}" + Fore.RESET)
        return False

    log(Fore.GREEN + "[OK] VergeGridMySQL service registered successfully." + Fore.RESET)
    return True


# ============================================================
# MySQL Start Service
# ============================================================

def start_mysql_service():
    """Start VergeGridMySQL service with raw command visibility."""
    log = _get_logger()
    proc = subprocess.Popen("sc start VergeGridMySQL", stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=True)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        log(Fore.RED + f"[ERROR] Failed to start service: {stderr or stdout}" + Fore.RESET)
        return False
    for i in range(10):
        success, status = run_cmd(["sc", "query", "VergeGridMySQL"])
        if "RUNNING" in status:
            log(Fore.GREEN + "[OK] MySQL service is running successfully." + Fore.RESET)
            return True
        time.sleep(1)
    log(Fore.RED + "[FAIL] MySQL service did not reach RUNNING state." + Fore.RESET)
    return False

# ============================================================
# Password Handling
# ============================================================

def prompt_root_password():
    print(Style.BRIGHT + Fore.CYAN + "\nMySQL Root Account Setup" + Fore.RESET)
    safe_specials = "@#$%^&*_-+!?"
    invalid_chars = set(' "\'\\/:;<>|()[]{}=,.~`')
    while True:
        pw1 = input(Fore.GREEN + "Enter new MySQL root password: " + Fore.RESET).strip()
        pw2 = input(Fore.GREEN + "Confirm password: " + Fore.RESET).strip()
        if pw1 != pw2:
            print(Fore.RED + "Passwords do not match.\n"); continue
        if len(pw1) < 10 or any(ch in invalid_chars for ch in pw1) or not re.search(r"[A-Z]", pw1) or not re.search(r"[a-z]", pw1) or not re.search(r"[0-9]", pw1) or not any(ch in safe_specials for ch in pw1):
            print(Fore.RED + "Password does not meet requirements.\n"); continue
        print(Fore.CYAN + f"\nRoot password confirmed: {pw1}\n" + Fore.RESET)
        return pw1

# ============================================================
# Main Setup Routine (Patched & Path-Safe)
# ============================================================

def setup_mysql(root: Path):
    log = _get_logger()
    log(Style.BRIGHT + Fore.CYAN + "\n=== VergeGrid MySQL Setup (Path-Safe) ===" + Fore.RESET)

    try:
        # --- Normalize path ---
        if not (root / "MySQL").exists() and (root.parent / "MySQL").exists():
            log(Fore.YELLOW + f"[FIX] Adjusting MySQL root from {root} → {root.parent}" + Fore.RESET)
            root = root.parent

        mysql_root = root / "MySQL"
        data_dir = mysql_root / "data"
        os.makedirs(data_dir, exist_ok=True)

        # Fix nested directories if present
        nested = mysql_root / "MySQL"
        if nested.exists() and (nested / "bin" / "mysqld.exe").exists():
            log(Fore.YELLOW + f"[FIX] Detected nested MySQL directory: {nested}" + Fore.RESET)
            for item in nested.iterdir():
                dest = mysql_root / item.name
                if not dest.exists():
                    shutil.move(str(item), str(dest))
            shutil.rmtree(nested, ignore_errors=True)
            log(Fore.CYAN + "[FIX] Corrected nested MySQL structure." + Fore.RESET)

        # --- Proceed with setup ---
        if not generate_mysql_ini(root):
            log(Fore.RED + "[ABORT] Could not create MySQL config." + Fore.RESET)
            return False
        if not initialize_mysql_data(root):
            log(Fore.RED + "[ABORT] MySQL initialization failed." + Fore.RESET)
            return False
        if not create_mysql_service(root):
            log(Fore.RED + "[ABORT] Service creation failed." + Fore.RESET)
            return False
        if not start_mysql_service():
            log(Fore.RED + "[ABORT] Service startup failed." + Fore.RESET)
            return False

        pw = prompt_root_password()

        # --- Apply the root password immediately ---
        log(Fore.CYAN + "[ACTION] Applying MySQL root password..." + Fore.RESET)
        mysql_exe = root / "MySQL" / "bin" / "mysql.exe"

        # Give MySQL a few seconds to be sure it’s fully ready to accept connections
        time.sleep(5)

        try:
            cmd = [
                str(mysql_exe),
                "-u", "root",
                "-e",
                f"ALTER USER 'root'@'localhost' IDENTIFIED BY '{pw}'; FLUSH PRIVILEGES;"
            ]
            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.returncode == 0:
                log(Fore.GREEN + "[OK] MySQL root password applied successfully." + Fore.RESET)
            else:
                log(Fore.RED + f"[ERROR] Failed to apply root password:\n{result.stderr or result.stdout}" + Fore.RESET)

        except Exception as e:
            log(Fore.RED + f"[FATAL] Exception while applying root password: {e}" + Fore.RESET)

        log(Fore.GREEN + "\n[SUCCESS] VergeGrid MySQL service is up and running." + Fore.RESET)
        log(Fore.CYAN + "[COMPLETE] MySQL setup finished cleanly.\n" + Fore.RESET)
        return True

    except Exception as e:
        log(Fore.RED + f"[FATAL] Exception during setup: {e}" + Fore.RESET)
        return False

# ============================================================
# Script Entry
# ============================================================

if __name__ == "__main__":
    print(Style.BRIGHT + Fore.CYAN + "\n=== VergeGrid MySQL Standalone Setup ===" + Fore.RESET)
    install_root = Path("D:\\VergeGrid")
    os.makedirs(install_root, exist_ok=True)
    success = setup_mysql(install_root)
    if success:
        print(Style.BRIGHT + Fore.GREEN + "\n[COMPLETE] MySQL setup finished successfully." + Fore.RESET)
    else:
        print(Style.BRIGHT + Fore.RED + "\n[FAILED] MySQL setup encountered errors. Check logs for details." + Fore.RESET)
