#!/usr/bin/env python3
# ==============================================================
# VergeGrid Initial Landing Estate Generator (DreamGrid Style)
# Creates:
#   • Regions\Landings\Moonlight Landing.ini
#   • Regions\Landings\Landings.ini (OpenSim override)
# HyperGrid-ready, no console prompts on first OpenSim startup.
# ==============================================================
import os
import sys
import uuid
import socket
import mysql.connector
from cryptography.fernet import Fernet
from configparser import ConfigParser

# --------------------------------------------------------------
# PATHS AND DEFAULTS
# --------------------------------------------------------------
OPENSIM_BIN = r"D:\VergeGrid\OpenSim\bin"
REGIONS_BASE = os.path.join(OPENSIM_BIN, "Regions")
ESTATE_DIR = os.path.join(REGIONS_BASE, "Landings")

CREDS_FILE = os.path.join(os.path.dirname(__file__), "creds.conf")
VAULT_FILE = os.path.join(os.path.dirname(__file__), "vault.key")

# Default region configuration
DEFAULT_REGION_NAME = "Moonlight Landing"
DEFAULT_ESTATE_NAME = "Landings Estate"
DEFAULT_LOCATION_BASE = (9300, 9300)  # starting map coords
DEFAULT_INTERNAL_PORT_BASE = 8005     # starting internal port
DEFAULT_GROUP_PORT = 8008
DEFAULT_PHYSICS_ENGINE = 3
DEFAULT_MAX_AGENTS = 100
DEFAULT_MAX_PRIMS = 45000

# --------------------------------------------------------------
# HELPER FUNCTIONS
# --------------------------------------------------------------
def load_encrypted_password(user="robustuser"):
    """Decrypt password from creds.conf using vault.key."""
    if not os.path.exists(CREDS_FILE) or not os.path.exists(VAULT_FILE):
        print("[FATAL] Missing creds.conf or vault.key. Run secure_mysql_root.py first.")
        sys.exit(1)

    with open(VAULT_FILE, "rb") as f:
        key = f.read()
    fernet = Fernet(key)

    cfg = ConfigParser()
    cfg.read(CREDS_FILE, encoding="utf-8")

    try:
        encrypted_pw = cfg["Encrypted"][user]
        return fernet.decrypt(encrypted_pw.encode()).decode()
    except Exception as e:
        print(f"[ERROR] Unable to decrypt {user} password: {e}")
        sys.exit(1)


def fetch_god_uuid():
    """Fetch VergeGrid 'God' user UUID (UserLevel >= 250)."""
    print("[INFO] Connecting to MySQL to find God user...")
    pw = load_encrypted_password("robustuser")

    try:
        conn = mysql.connector.connect(
            host="localhost",
            user="robustuser",
            password=pw,
            database="robust"
        )
        cur = conn.cursor()
        cur.execute("SELECT PrincipalID, FirstName, LastName FROM useraccounts WHERE UserLevel >= 250 LIMIT 1;")
        result = cur.fetchone()
        cur.close()
        conn.close()
        if result:
            uuid_, first, last = result
            print(f"[OK] Found God user: {first} {last} ({uuid_})")
            return uuid_
        else:
            print("[WARN] No God user found, using random UUID.")
            return str(uuid.uuid4())
    except mysql.connector.Error as err:
        print(f"[ERROR] MySQL error: {err}")
        sys.exit(1)


def next_region_settings():
    """Automatically assign next available region coordinates and port."""
    os.makedirs(ESTATE_DIR, exist_ok=True)
    existing_files = [f for f in os.listdir(ESTATE_DIR) if f.endswith(".ini") and f != "Landings.ini"]

    # Increment by 1 per region
    offset = len(existing_files)
    x = DEFAULT_LOCATION_BASE[0] + offset
    y = DEFAULT_LOCATION_BASE[1]
    port = DEFAULT_INTERNAL_PORT_BASE + offset
    return (x, y, port)


def create_region_ini(owner_uuid):
    """Generate DreamGrid-style region configuration file."""
    os.makedirs(ESTATE_DIR, exist_ok=True)
    (x, y, port) = next_region_settings()
    region_file = os.path.join(ESTATE_DIR, f"{DEFAULT_REGION_NAME}.ini")
    region_uuid = str(uuid.uuid4())

    # Get the local IP for ExternalHostName
    try:
        ip = socket.gethostbyname(socket.gethostname())
    except Exception:
        ip = "127.0.0.1"

    content = f"""; * VergeGrid Region Configuration File
; Automatically generated by init-landing.py
; Compatible with DreamGrid/OpenSim format.
[{DEFAULT_REGION_NAME}]
AllowAlternatePorts=False
AllowGods=True
Birds=False
ClampPrimSize=False
Concierge=False
Cores=255
DefaultLanding=<128,128,30>
DisableGloebits=False
DisallowForeigners=False
DisallowResidents=False
Enabled=True
Estate={DEFAULT_ESTATE_NAME}
ExternalHostName={ip}
FrameTime=0.09
GodDefault=False
GroupPort={DEFAULT_GROUP_PORT}
InternalAddress=0.0.0.0
InternalPort={port}
Location={x},{y}
Locked=False
ManagerGod=False
MaptileStaticFile=
MapType=Best
MaxAgents={DEFAULT_MAX_AGENTS}
MaxPrims={DEFAULT_MAX_PRIMS}
MinTimerInterval=0.2
NonPhysicalPrimMax=1024
OpensimWorldAPIKey=
PhysicalPrimMax=64
Physics={DEFAULT_PHYSICS_ENGINE}
Publicity=
RegionGod=False
RegionSnapShot=True
RegionType=Estate
RegionUUID={region_uuid}
ScriptEngine=
SizeX=256
SizeY=256
SkipAutoBackup=False
SmartBoot=False
SmartStart=False
Teleport=True
Tides=False
GenerateMaptiles=True
MapImageModule=Warp3DImageModule
TextureOnMapTile=True
DrawPrimOnMapTile=True
TexturePrims=True
RenderMeshes=True
EstateOwner={owner_uuid}
"""

    with open(region_file, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] Created region configuration: {region_file}")
    print(f"     Region UUID: {region_uuid}")
    print(f"     Port: {port}")
    print(f"     Location: {x},{y}")


def create_estate_override_ini():
    """Generate the estate-specific OpenSim override (same folder as region)."""
    estate_file = os.path.join(ESTATE_DIR, "Landings.ini")
    opensim_ini_path = os.path.join(OPENSIM_BIN, "OpenSim.ini").replace("\\", "/")

    content = f"""; VergeGrid Simulator Override - Landings
; HG-ready lightweight instance configuration
; Auto-generated by init-landing.py

[Startup]
; Use absolute path to include the full OpenSim configuration chain
include-ini = "{opensim_ini_path}"

; Override region directory and prompt
regionload_regionsdir = "./Regions/Landings"
ConsolePrompt = "Landings# "
create_default_region = false

[Network]
; Internal HTTP listener port (starts at 8005)
http_listener_port = {DEFAULT_INTERNAL_PORT_BASE}

[Physics]
physics = ubOde

[GridService]
GridName = VergeGrid Landings

[Hypergrid]
hypergrid_enabled = true
"""

    with open(estate_file, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] Created estate override: {estate_file}")


# --------------------------------------------------------------
# MAIN ROUTINE
# --------------------------------------------------------------
def main():
    print("\n=== VergeGrid Landing Estate Initializer (DreamGrid Style) ===")
    owner_uuid = fetch_god_uuid()
    create_region_ini(owner_uuid)
    create_estate_override_ini()

    print("\n✅ Landing estate fully initialized!")
    print("   To start your simulator, run:")
    print(r"   OpenSim.exe -inifile=Regions\Landings\Landings.ini\n")


if __name__ == "__main__":
    main()
