#!/usr/bin/env python3
# VergeGrid MySQL Initialization Utility (Insecure Mode)
# Author: Sonja + GPT
# Purpose: Initialize MySQL with no root password (insecure mode)
#          Service install + run verification only.
#          Root password setup deferred to separate script.

import os
import sys
import subprocess
import time
import re
import shutil
from datetime import datetime
from pathlib import Path
from colorama import Fore, Style, init
init(autoreset=True, strip=False, convert=True)
from vergegrid_common import _get_logger

# --- VergeGrid Path Fix ---
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)
# --- End Fix ---

# ============================================================
# Templates
# ============================================================

MYSQL_TEMPLATE = r"""
# VergeGrid MySQL Configuration (Insecure Debug Mode)
# Auto-generated by VergeGrid Installer
[client]
port=3306
socket="%(root)s\\MySQL\\mysql.sock"

[mysql]
default-character-set=utf8mb4

[mysqld]
basedir="%(root)s\\MySQL"
datadir="%(root)s\\MySQL\\data"
port=3306
socket="%(root)s\\MySQL\\mysql.sock"
pid_file="%(root)s\\MySQL\\data\\mysql.pid"

# --- Enhanced Debug Logging ---
log_error_verbosity=3
general_log=1
general_log_file="%(root)s\\MySQL\\logs\\mysql-general.log"
log_error="%(root)s\\MySQL\\logs\\mysql-error.log"
slow_query_log=1
slow_query_log_file="%(root)s\\MySQL\\logs\\mysql-slow.log"

# --- Core Options ---
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
max_connections=500
connect_timeout=15
wait_timeout=28800
interactive_timeout=28800
innodb_buffer_pool_size=512M
innodb_redo_log_capacity=536870912
innodb_flush_log_at_trx_commit=2
innodb_file_per_table=1
innodb_flush_method=normal
innodb_lock_wait_timeout=120

# --- Binary Logging ---
log-bin="%(root)s\\MySQL\\data\\mysql-bin"
binlog_format=row
binlog_expire_logs_seconds=604800
sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
server-id=1
"""

# ============================================================
# Utility helpers
# ============================================================

def run_cmd(cmd, cwd=None, timeout=None, label="CMD"):
    """Run a subprocess with live output streaming and full logging."""
    log = _get_logger()

    # Dynamic log directory based on install_root if available
    default_log_dir = Path.cwd() / "MySQL" / "logs"
    log_dir = os.environ.get("VERGEGRID_INSTALL_ROOT", str(default_log_dir))
    log_dir = Path(log_dir) / "MySQL" / "logs"

    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = log_dir / f"{label.replace(' ', '_')}_{timestamp}.log"

    log(Fore.YELLOW + f"[DEBUG] Running command: {' '.join(cmd)}" + Fore.RESET)
    with open(log_file, "w", encoding="utf-8") as f:
        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )
        for line in iter(proc.stdout.readline, ''):
            print(Fore.CYAN + f"[{label}] " + Fore.RESET + line.strip())
            f.write(line)
        proc.wait(timeout=timeout)
    log(Fore.GREEN + f"[DEBUG] Output written to {log_file}" + Fore.RESET)
    return proc.returncode


# ============================================================
# Core Setup Logic
# ============================================================

def generate_mysql_ini(mysql_root: Path):
    log = _get_logger()
    conf_path = mysql_root / "my.ini"
    conf_text = MYSQL_TEMPLATE % {"root": str(mysql_root.parent)}

    # Cleanup and ensure directories
    data_dir = mysql_root / "data"
    if data_dir.exists():
        for item in data_dir.iterdir():
            try:
                if item.is_file():
                    item.unlink()
                else:
                    shutil.rmtree(item)
            except Exception as e:
                log(Fore.YELLOW + f"[WARN] Could not remove {item}: {e}" + Fore.RESET)
    os.makedirs(data_dir, exist_ok=True)

    logs_path = mysql_root / "logs"
    logs_path.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(conf_text, encoding="utf-8")
    log(Fore.GREEN + f"[OK] Created MySQL config (insecure mode): {conf_path}" + Fore.RESET)
    return conf_path


def initialize_mysql_data(mysql_root: Path):
    """Initialize MySQL data directory WITHOUT secure mode (no password)."""
    log = _get_logger()
    data_dir = mysql_root / "data"
    mysqld = mysql_root / "bin" / "mysqld.exe"
    log_file = data_dir / "init_error.log"

    if not mysqld.exists():
        log(Fore.RED + f"[ERROR] mysqld.exe not found at {mysqld}" + Fore.RESET)
        return None

    os.makedirs(data_dir, exist_ok=True)
    log(Fore.YELLOW + "[INIT] Running MySQL INSECURE initialization (no password mode)..." + Fore.RESET)

    cmd = [
        str(mysqld),
        "--initialize-insecure",
        "--console",
        f"--basedir={mysql_root}",
        f"--datadir={data_dir}",
        f"--log-error={log_file}"
    ]

    rc = run_cmd(cmd, label="MySQLInit-Insecure")
    if rc != 0:
        log(Fore.RED + f"[ERROR] MySQL initialization returned code {rc}" + Fore.RESET)
        if log_file.exists():
            print(log_file.read_text(errors='ignore'))
        return None

    log(Fore.GREEN + "[OK] MySQL insecure initialization completed successfully." + Fore.RESET)

    subprocess.run(["taskkill", "/F", "/IM", "mysqld.exe"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(2)
    log(Fore.GREEN + "[CLEANUP] MySQL processes terminated." + Fore.RESET)
    return ""


def create_mysql_service(mysql_root: Path):
    log = _get_logger()
    mysqld = mysql_root / "bin" / "mysqld.exe"
    ini_file = mysql_root / "my.ini"

    log(Fore.YELLOW + "[CREATE] Installing VergeGridMySQL service..." + Fore.RESET)
    subprocess.run(["sc", "stop", "VergeGridMySQL"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.run(["sc", "delete", "VergeGridMySQL"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    rc = run_cmd([str(mysqld), "--install", "VergeGridMySQL", f"--defaults-file={ini_file}"], label="ServiceInstall")
    if rc == 0:
        log(Fore.GREEN + "[OK] VergeGridMySQL service registered successfully." + Fore.RESET)
        return True

    log(Fore.RED + "[ERROR] Failed to install VergeGridMySQL service. Check ServiceInstall log." + Fore.RESET)
    return False


def start_mysql_service():
    log = _get_logger()
    log(Fore.YELLOW + "[DEBUG] Attempting to start VergeGridMySQL service..." + Fore.RESET)
    run_cmd(["sc", "start", "VergeGridMySQL"], label="ServiceStart")

    for _ in range(30):
        status = subprocess.run(["sc", "query", "VergeGridMySQL"], capture_output=True, text=True).stdout
        if "RUNNING" in status:
            log(Fore.GREEN + "[OK] VergeGridMySQL service is running." + Fore.RESET)
            run_cmd(["netstat", "-ano"], label="NetstatCheck")
            return True
        time.sleep(2)

    log(Fore.RED + "[FAIL] Service did not reach RUNNING state after 60s." + Fore.RESET)
    run_cmd(["sc", "query", "VergeGridMySQL"], label="ServiceQuery")
    return False


# ============================================================
# Main Setup
# ============================================================

def setup_mysql(root: Path):
    log = _get_logger()
    log(Style.BRIGHT + Fore.CYAN + "\n=== VergeGrid MySQL Setup (Insecure Mode) ===" + Fore.RESET)

    if (root / "bin" / "mysqld.exe").exists():
        mysql_root = root
        log(Fore.CYAN + f"[INFO] Using provided MySQL root: {mysql_root}" + Fore.RESET)
    elif (root / "MySQL" / "bin" / "mysqld.exe").exists():
        mysql_root = root / "MySQL"
        log(Fore.YELLOW + f"[FIX] Adjusted MySQL root to: {mysql_root}" + Fore.RESET)
    else:
        log(Fore.RED + f"[ERROR] Could not locate mysqld.exe under {root}" + Fore.RESET)
        return False

    os.makedirs(mysql_root / "data", exist_ok=True)
    generate_mysql_ini(mysql_root)
    temp_pw = initialize_mysql_data(mysql_root)
    if temp_pw is None:
        return False
    if not create_mysql_service(mysql_root):
        return False
    if not start_mysql_service():
        return False

    log(Fore.YELLOW + "[SKIP] Secure password setup skipped (insecure mode enabled)." + Fore.RESET)
    mysql_exe = mysql_root / "bin" / "mysql.exe"

    log(Fore.YELLOW + "[TEST] Verifying MySQL root login (no password)..." + Fore.RESET)
    for i in range(30):
        test = subprocess.run(
            [str(mysql_exe), "-u", "root", "-e", "SELECT 1;"],
            capture_output=True, text=True
        )
        if test.returncode == 0:
            log(Fore.GREEN + "[OK] MySQL root login works (no password)." + Fore.RESET)
            break
        else:
            log(Fore.YELLOW + f"[WAIT] Attempt {i+1}/30: {test.stderr.strip()}" + Fore.RESET)
        time.sleep(2)
    else:
        log(Fore.RED + "[ERROR] MySQL did not respond to root login after 60s." + Fore.RESET)
        return False

    log(Fore.GREEN + "\n[SUCCESS] VergeGrid MySQL service is up and running (INSECURE MODE)." + Fore.RESET)
    log(Fore.YELLOW + "[NOTE] Root account currently has NO PASSWORD. Run secure-mysql.py later to lock it down." + Fore.RESET)
    return True


# ============================================================
# Entry Point (Dynamic)
# ============================================================

if __name__ == "__main__":
    print(Style.BRIGHT + Fore.CYAN + "\n=== VergeGrid MySQL Initialization (Dynamic Insecure Mode) ===" + Fore.RESET)
    if len(sys.argv) < 2:
        print("Usage: python init-mysql.py <install_root>")
        sys.exit(1)

    install_root = Path(sys.argv[1])
    os.environ["VERGEGRID_INSTALL_ROOT"] = str(install_root)

    if setup_mysql(install_root):
        print(Fore.GREEN + "[COMPLETE] MySQL setup finished successfully (insecure mode)." + Fore.RESET)
    else:
        print(Fore.RED + f"[FAILED] MySQL setup encountered errors. Check {install_root}\\MySQL\\logs." + Fore.RESET)
